### ISSUE TITLE
[FEATURE] Roadmap Masterlist

### ISSUE THREAD

**Issue by ricafolio** [ricafolio/react-canvas-collage-maker#13]
## Features roadmap
**Template**
  - [ ] Retain uploaded image when changing template
    - [ ] (Temporary) Show warning before changing template
    - [ ] Set index on uploaded image

**UI**
  - [x] #17 on canvas
    - [x] Delete footer
    - [x] Move `Download collage` on top right of menu bar
    - [x] Add github & creator icon on left of download button

**Canvas**
- [ ] Reset canvas
- [ ] Uploaded image options
  - [ ] Replace image button
  - [ ] Delete image button
  - [ ] Vertically center image
  - [ ] Horizontally center image
- [ ] Add "Select image" text on cells
- [x] #19
- [x] #20

**Filters**
- [ ] Add more filter options
- [ ] Remove blur filter

**Others**
- [ ] Meta tags

### Fabric.js resources
- http://fabricjs.com/demos/
- http://fabricjs.com/docs/
